### ISSUE TITLE
 ModuleNotFoundError: No module named 'psm.utils'; 'psm' is not a package

### ISSUE THREAD

**Issue by Afraz85** [ahilbers/renewable_test_PSMs#6]
Hi, when I am trying to run models.py in spyder from psm I get the subject  error.
I already have installed psm package.
Can you please tell me the issue

**Comment by ahilbers** [comment]
Mhmm, that's weird. I tried to reinstall `psm` for me in a new environment, and everything seems to work fine.

The most common reason for these errors is, in my experience, when python is loading a different `psm` then the one you've installed. This often happens when you've manually created a python file called `psm.py`, or a new directory called `psm`, so the local import overrides the package import.

It's a bit difficult to give an answer to your problem without more details. Some things that might help identify what's going on:
- What's the code you are trying to run?
- What is the filename, and directory structure, of the files you're trying to run? (e.g. is your script located in `psm/experiments.py`, or something like that?
- From what directory are you trying to run it?

**Comment by Afraz85** [comment]
Thanks for your reply. I have reinstall and then installed the psm again. But nothing has been changed. I am using spyder to run model.py file which is in the path: [renewable_test_PSMs](https://github.com/ahilbers/renewable_test_PSMs)/psm/.

Please see the attachment as well. 
<img width="1005" alt="Screenshot 2022-03-20 at 13 37 33" src="https://user-images.githubusercontent.com/58227413/159162734-45394c56-c768-4483-92da-c86594cdc16a.png">

**Comment by ahilbers** [comment]
Are you in Spyder, and using the green "run" play button to run `models.py`? If so, this might be the source of the problem. `models.py` isn't a script, so it's not designed to be run, but usually imported.

Can you try running the following commands from a terminal / command line (so not from Spyder):

```
cd renewable_test_PSMs  # Just enter the PSM directory
python3 scripts/main.py
```

Does that work? I see you've also opened an issue on CBC about failing to install that, so I guess you'll get errors when actually solving the model. But I'm interested whether you get any `ImportError` or `ModuleNotFoundError` problems.

**Comment by Afraz85** [comment]
Yes it was me. I have configured cbc now. Now trying to run the example that you have shared. It looks intresting to me. Can you please see the output of terminal. I am not clear what it says.
[renewable_out.txt](https://github.com/ahilbers/renewable_test_PSMs/files/8311273/renewable_out.txt)

**Comment by Afraz85** [comment]
And instead of spyder, now I am running with jupytor. But unable to get the output. It seems that I am unable to run: model . run().
<img width="382" alt="Screenshot 2022-03-20 at 14 43 59" src="https://user-images.githubusercontent.com/58227413/159165574-697bb807-9141-454c-9ef1-8fa1f7f44bb4.png">

**Comment by ahilbers** [comment]
At this point, what's going on is exactly what's said in the error messages. In the first case, it's that the model wants to save its results to a directory called `outputs`, but it's giving a warning that it already exists. So you just have to delete it and start over.

In the second case, something went wrong with the optimisation problem. Did you manage to install `cbc`? If not, this is what's going wrong -- the model creates an optimisation problem, which it sends to the solver `cbc` to solve. But if `cbc` isn't installed or isn't working, then you get an error. From there, anything which relies on the model results will fail (since these haven't been calculated). That's why the two subsequent cells fail. The first is saying you need to calculate the results by calling `model.run()`, but you tried that above and it failed. 

See if you can get `cbc` working, then this should all run.

**Comment by Afraz85** [comment]
Thanks for helping me out. I deleted that directory of output. It looks that cbc is installed on my machine. See the attached file.

I am able to run cbc in other files as well. But indeed the problem here is with cbc with jupytor. 
[cbc_status.txt](https://github.com/ahilbers/renewable_test_PSMs/files/8314448/cbc_status.txt)

**Comment by ahilbers** [comment]
It could be an issue with jupyter, or python failing to connect to `cbc`. Can you try running `python3 scripts/main.py` to see if that works?

**Comment by Afraz85** [comment]
@ahilbers , yes I am checking it. I will let you know. Thanks

**Comment by ahilbers** [comment]
I'm going to close this issue for now, as it's been inactive and deviated a bit from the original issue. If you've got any more problems, feel free to get back in touch.

**Comment by Afraz85** [comment]
Thanks Ahilbers/Renewable_test_psms
*Best Regards *
*Afraz Mehmood*

*+32 465 91 38 21*
